### ISSUE TITLE
Can't import streamlit after !pip install -qU unpackai[deploy]. 

### ISSUE THREAD

**Issue by faizer1989** [unpackAI/unpackai#82]
**Can't import streamlit after !pip install -qU unpackai[deploy].** 

After import streamlit as st, it throws an error: ContextualVersionConflict: (ipykernel 4.10.1 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('ipykernel>=5.1.2; python_version >= "3.4"'), {'pydeck'})

![error capture](https://user-images.githubusercontent.com/29976206/142578055-e5ea51bb-9531-4c92-8c76-7aba72b8a171.png)

[colab notebook](https://colab.research.google.com/drive/1iVsUO6vrsnVmg4xPFvFTbMmA3-PwmRLZ#scrollTo=UkdkCZkV7CUn)

**Comment by jfthuong** [comment]
![image](https://user-images.githubusercontent.com/1401809/142641787-8d668ab6-6344-448a-8abd-6ceedd0be147.png)


1. Installation is indeed via `!pip install unpackai[deploy]` that installs the extra dependencies for deployment (`streamlit` in particular)
2. Streamlit shall not be used directly in jupyter but rather in the code of the app so **don't do `import streamlit as st` in a cell** (unless you have the magics `%%writefile app.py` at the top to write in a file)
3. Write the code of the app either via `%%writefile app.py` or `StreamlitApp("CV").render_fastai(......).save()`

Then it will work.

Note: for deployment, it's better to export the model rather than save `learn.export("model.pkl")` because then you can just reload it in your app without having to create a new learning and add the learned weights.

**Comment by jfthuong** [comment]
And after that, you can just run in a new cell:

```python
deploy_app()
```
 
or `deploy_app("app.py")` (or whatever you named your app) to run it.

**Comment by jfthuong** [comment]
https://colab.research.google.com/gist/jfthuong/e926c35ba6cefd2de471814581dcc0c3/01_cv_coursebook.ipynb#scrollTo=6atd2mkw6fw9

See here for reference
